# yoga_app/forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth import authenticate
from .models import (
    Booking,
    Testimonial,
    NewsletterSubscription,
    ContactMessage,
    UserProfile,
    CourseReview,
    DiscussionTopic,
    DiscussionPost,
    Lesson,
    LessonComment,
    BlogPostCategory, BlogPost, BlogComment # NEW: Import Blog models
)

# Common Tailwind CSS classes for form inputs
TAILWIND_INPUT_CLASSES = 'w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-500'


# Form for User Registration
class UserRegisterForm(UserCreationForm):
    """
    Custom form for user registration. Extends Django's UserCreationForm.
    Applies consistent styling to all fields without duplication.
    """
    email = forms.EmailField(
        required=True,
        label="Email Address",
        widget=forms.EmailInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your email address'})
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)
        widgets = {
            'username': forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Choose a username'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Apply Tailwind classes to all fields, including password fields generated by UserCreationForm
        for field_name, field in self.fields.items():
            if isinstance(field.widget, (forms.PasswordInput,)):
                field.widget.attrs['class'] = TAILWIND_INPUT_CLASSES
                if field_name == 'password1':
                    field.widget.attrs['placeholder'] = 'Enter your password'
                elif field_name == 'password2':
                    field.widget.attrs['placeholder'] = 'Confirm your password'
            # Also apply to username and email if they weren't already set by widgets in Meta
            elif field_name in ['username', 'email'] and 'class' not in field.widget.attrs:
                 field.widget.attrs['class'] = TAILWIND_INPUT_CLASSES


    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already registered.")
        return email

# Form for User Login
class UserLoginForm(AuthenticationForm):
    """
    Custom form for user login. Extends Django's AuthenticationForm.
    Primarily used for rendering with custom styling and allowing email/username login.
    """
    username = forms.CharField(
        label="Username or Email",
        widget=forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Enter your username or email'})
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Enter your password'})
    )
    
    # Override the clean method to allow login by email or username
    def clean(self):
        # Call the parent's clean method first to get initial validation errors
        # and populate self.cleaned_data
        super().clean() 

        username_or_email = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username_or_email and password:
            # Try to authenticate with username first
            self.user_cache = authenticate(self.request, username=username_or_email, password=password)

            # If username authentication fails, try with email
            if self.user_cache is None and '@' in username_or_email:
                try:
                    user_obj = User.objects.get(email=username_or_email)
                    self.user_cache = authenticate(self.request, username=user_obj.username, password=password)
                except User.DoesNotExist:
                    pass # User not found by email, authentication remains None

            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            elif not self.user_cache.is_active:
                raise forms.ValidationError(
                    self.error_messages['inactive'],
                    code='inactive',
                )
        return self.cleaned_data


# Form for updating User account (username and email)
class UserAccountUpdateForm(forms.ModelForm):
    username = forms.CharField(required=True, label="Username",
                               widget=forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your new username'}))
    email = forms.EmailField(required=True, label="Email Address",
                             widget=forms.EmailInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your new email address'}))

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This username is already taken by another user.")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This email is already taken by another user.")
        return email

# Form for updating UserProfile (profile picture and bio)
class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(
        required=False,
        label="Profile Picture",
        widget=forms.ClearableFileInput(attrs={'class': 'w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-500'})
    )
    bio = forms.CharField(
        required=False,
        label="About Me / Bio",
        widget=forms.Textarea(attrs={'rows': 4, 'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Tell us a little about yourself...'}),
    )

    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'bio']


# Form for Password Change
class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Apply Tailwind classes to all password fields
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = TAILWIND_INPUT_CLASSES
            if field_name == 'old_password':
                field.widget.attrs['placeholder'] = 'Enter your current password'
            elif field_name == 'new_password1':
                field.widget.attrs['placeholder'] = 'Enter your new password'
            elif field_name == 'new_password2':
                field.widget.attrs['placeholder'] = 'Confirm your new password'


# Form for Booking a Private Session
class BookingForm(forms.ModelForm):
    preferred_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': TAILWIND_INPUT_CLASSES}),
        label="Preferred Date"
    )
    preferred_time = forms.ChoiceField(
        choices=Booking.TIME_CHOICES,
        widget=forms.Select(attrs={'class': TAILWIND_INPUT_CLASSES}),
        label="Preferred Time"
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class': TAILWIND_INPUT_CLASSES + ' rows-4', 'placeholder': 'Any specific requests or questions?'}),
        required=False,
        label="Your Message"
    )

    class Meta:
        model = Booking
        fields = ['full_name', 'email', 'preferred_date', 'preferred_time', 'message']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Enter your name'}),
            'email': forms.EmailInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Enter your email'}),
        }
        labels = {
            'full_name': 'Full Name',
            'email': 'Email',
        }


# Form for Submitting Testimonials/Feedback
class TestimonialForm(forms.ModelForm):
    rating = forms.IntegerField(
        min_value=1,
        max_value=5,
        required=True,
        widget=forms.HiddenInput(attrs={'id': 'id_rating_testimonial'}),
        error_messages={'required': 'Please select a rating.'}
    )

    class Meta:
        model = Testimonial
        fields = ['author_name', 'email', 'rating', 'feedback_text']
        widgets = {
            'author_name': forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your name'}),
            'email': forms.EmailInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your email'}),
            'feedback_text': forms.Textarea(attrs={'class': TAILWIND_INPUT_CLASSES + ' rows-4', 'placeholder': 'Share your experience with us'}),
        }
        labels = {
            'author_name': 'Name',
            'email': 'Email',
            'feedback_text': 'Your Feedback',
        }

# Form for Newsletter Subscription
class NewsletterSubscriptionForm(forms.ModelForm):
    class Meta:
        model = NewsletterSubscription
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'px-4 py-2 rounded-l-lg focus:outline-none text-gray-800 w-full', 'placeholder': 'Your email'}),
        }
        labels = {
            'email': '',
        }

# Form for Contact Message (used if the general feedback form is distinct from testimonials)
class ContactMessageForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'subject', 'message'] # Added 'subject' field
        widgets = {
            'name': forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your name'}),
            'email': forms.EmailInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Your email'}),
            'subject': forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Subject of your message'}), # Widget for subject
            'message': forms.Textarea(attrs={'class': TAILWIND_INPUT_CLASSES + ' rows-4', 'placeholder': 'Your message'}),
        }
        labels = {
            'name': 'Full Name',
            'email': 'Email',
            'subject': 'Subject', # Label for subject
            'message': 'Your Message',
        }

# Form for Course Review
class CourseReviewForm(forms.ModelForm):
    rating = forms.IntegerField(
        widget=forms.HiddenInput(),
        min_value=1,
        max_value=5,
        required=True
    )
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'class': TAILWIND_INPUT_CLASSES + ' rows-4', 'placeholder': 'Write your review here...'}),
        required=False
    )

    class Meta:
        model = CourseReview
        fields = ['rating', 'comment']
        labels = {
            'comment': 'Your Comment',
        }
    

# Form for creating a new Discussion Topic
class DiscussionTopicForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 10, 'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Start your discussion here...'}),
        label="Topic Content"
    )
    
    lesson = forms.ModelChoiceField(
        queryset=Lesson.objects.none(),
        required=False,
        label="Relates to Lesson (Optional)",
        widget=forms.Select(attrs={'class': TAILWIND_INPUT_CLASSES})
    )

    class Meta:
        model = DiscussionTopic
        fields = ['title', 'content', 'lesson']
        widgets = {
            'title': forms.TextInput(attrs={'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Enter topic title'}),
        }
        labels = {
            'title': 'Topic Title',
        }

    def __init__(self, *args, **kwargs):
        course = kwargs.pop('course', None)
        super().__init__(*args, **kwargs)
        if course:
            self.fields['lesson'].queryset = Lesson.objects.filter(module__course=course).order_by('module__order', 'order')
            # Removed redundant self.fields['lesson'].required = False


# Form for creating a new Discussion Post (reply)
class DiscussionPostForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 5, 'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Type your reply here...'}),
        label="Your Reply"
    )

    class Meta:
        model = DiscussionPost
        fields = ['content']
        labels = {
            'content': 'Your Reply',
        }

# Form for Lesson Comments
class LessonCommentForm(forms.ModelForm):
    """
    Form for users to submit comments on a specific lesson.
    """
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4, 'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Write your comment here...'}),
        label="Your Comment"
    )

    class Meta:
        model = LessonComment
        fields = ['content']
        labels = {
            'content': 'Your Comment',
        }

# NEW: Form for Blog Comments
class BlogCommentForm(forms.ModelForm):
    """
    Form for users to submit comments on a specific blog post.
    """
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 4, 'class': TAILWIND_INPUT_CLASSES, 'placeholder': 'Write your comment here...'}),
        label="Your Comment"
    )

    class Meta:
        model = BlogComment
        fields = ['content']
        labels = {
            'content': 'Your Comment',
        }
