# Celery configuration
CELERY_BROKER_URL = 'redis://192.168.80.130:6379/16'
CELERY_RESULT_BACKEND = 'redis://192.168.80.130:6379/16'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

"""
Django settings for yoga_kailasa project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.ngrok-free.app', # Allow all ngrok-free.app subdomains
    'https://49640ad4bbe8.ngrok-free.app', # Or your specific ngrok subdomain
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'yoga_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yoga_kailasa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yoga_kailasa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB'),  # Your PostgreSQL database name
        'USER': os.environ.get('POSTGRES_USER'), # Your PostgreSQL user
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'), # Your PostgreSQL password
        'HOST': os.environ.get('POSTGRES_HOST'),       # Or the IP address of your PostgreSQL server
        'PORT': os.environ.get('POSTGRES_PORT'),                # Default PostgreSQL port is 5432. Leave empty for default.
    }
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake', # A unique string to identify this cache instance
        'TIMEOUT': 300, # Cache timeout in seconds (5 minutes)
        'OPTIONS': {
            'MAX_ENTRIES': 1000 # Maximum number of entries in the cache
        }
    }
}



# Paystack API Keys
# IMPORTANT: For production, load these from environment variables or a secure vault!
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY')
PAYSTACK_BASE_URL = 'https://api.paystack.co' # Base URL for Paystack API
PAYSTACK_WEBHOOK_URL='https://49640ad4bbe8.ngrok-free.app/payments/webhook/paystack/'  # Replace with your actual webhook URL


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, # Require a minimum of 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'yoga_app.validators.PasswordComplexityValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# AUTHENTICATION SETTINGS
LOGIN_REDIRECT_URL = 'home' # URL to redirect to after successful login
LOGOUT_REDIRECT_URL = 'home' # URL to redirect to after successful logout
LOGIN_URL = 'login' # URL for the login page

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Define the directory where Django will collect all static files for deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Define additional directories where Django will look for static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'yoga_app', 'static'), # Look for static files in your app's 'static' folder
    
]





# CKEDITOR 5 CONFIGURATION (NEW)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', '|', 'imageUpload', 'undo', 'redo'],
        # 'width': 'auto', # You can adjust width if needed
        # 'height': '400px', # You can adjust height if needed
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],
            'styles': [
                'full',
                'alignLeft',
                'alignRight'
            ]
        },
        'theme': 'lark', # 'lark' is the default theme for CKEditor 5
        'language': 'en',
    },
    'extends': { # Example of a custom configuration
        'toolbar': ['heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', '|', 'imageUpload', 'insertTable', 'mediaEmbed', '|', 'undo', 'redo'],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],
            'styles': [
                'full',
                'alignLeft',
                'alignRight'
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'media_embed': {
            'toolbar': ['mediaEmbed'],
        },
    },
    'super_full': { # Another example with more features
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link', 'bulletedList', 'numberedList',
            '|', 'blockQuote', 'codeBlock', 'htmlEmbed', 'sourceEditing',
            '|', 'imageUpload', 'insertTable', 'mediaEmbed',
            '|', 'undo', 'redo',
            '|', 'alignment', 'fontFamily', 'fontSize', 'fontColor', 'fontBackgroundColor', 'highlight', 'horizontalLine',
            '|', 'outdent', 'indent', 'removeFormat', 'specialCharacters',
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight'],
            'styles': [
                'full',
                'alignLeft',
                'alignRight'
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'media_embed': {
            'toolbar': ['mediaEmbed'],
        },
        'codeBlock': {
            'languages': [
                {'language': 'css', 'label': 'CSS'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'django', 'label': 'Django'},
                {'language': 'json', 'label': 'JSON'},
                {'language': 'bash', 'label': 'Bash'},
                {'language': 'plaintext', 'label': 'Plain text'},
            ]
        }
    }
}


# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Configuration for Password Reset
# For development, this prints emails to the console.
# For production, replace with your actual SMTP settings or a service like SendGrid, Mailgun etc.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Uncomment for real SMTP
# EMAIL_HOST = 'smtp.your-email-provider.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@example.com'
# EMAIL_HOST_PASSWORD = 'your_email_password'
DEFAULT_FROM_EMAIL = 'no-reply@yogakailasa.com' # The email address that sends the reset link
SERVER_EMAIL = DEFAULT_FROM_EMAIL # For error reporting
