# Generated by Django 5.2.3 on 2025-06-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the person booking.', max_length=100)),
                ('email', models.EmailField(help_text='Email address for communication regarding the booking.', max_length=254)),
                ('preferred_date', models.DateField(help_text='Preferred date for the session.')),
                ('preferred_time', models.CharField(choices=[('Morning (8am-12pm)', 'Morning (8am-12pm)'), ('Afternoon (12pm-4pm)', 'Afternoon (12pm-4pm)'), ('Evening (4pm-8pm)', 'Evening (4pm-8pm)')], help_text='Preferred time slot for the session.', max_length=50)),
                ('booked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was made.')),
            ],
        ),
        migrations.CreateModel(
            name='BreathingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the breathing technique.', max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, help_text='The Sanskrit name of the technique.', max_length=100, null=True)),
                ('description', models.TextField(help_text="A brief description of the technique's benefits.")),
                ('instructions', models.TextField(help_text='Step-by-step instructions for performing the breathing technique.')),
                ('duration', models.CharField(help_text="Recommended duration for the practice (e.g., '5-10 minutes daily').", max_length=50)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class for the technique (e.g., 'fas fa-wind').", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the consultant.', max_length=100)),
                ('specialty', models.CharField(help_text="Consultant's specialty (e.g., 'Yoga Therapist & Ayurveda Specialist').", max_length=200)),
                ('bio', models.TextField(help_text='A short biography of the consultant.')),
                ('icon_class', models.CharField(help_text="Font Awesome icon class for the consultant (e.g., 'fas fa-user-md').", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender.', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the sender.', max_length=254)),
                ('message', models.TextField(help_text='The content of the message.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was submitted.')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the yoga course.', max_length=200)),
                ('description', models.TextField(help_text='A detailed description of the course content.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the course. Use 0.00 for free courses.', max_digits=8)),
                ('is_free', models.BooleanField(default=False, help_text='Indicates if the course is free.')),
                ('instructor_name', models.CharField(help_text='Name of the course instructor.', max_length=100)),
                ('duration', models.CharField(help_text="Duration of the course (e.g., '4 weeks', '8 weeks').", max_length=50)),
                ('includes', models.TextField(blank=True, help_text="Comma-separated list of what the course includes (e.g., '12 poses, 3 breathing techniques').", null=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as true to highlight this course as popular.')),
                ('icon_class', models.CharField(help_text="Font Awesome icon class for the course (e.g., 'fas fa-heart').", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the subscriber.', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the subscription was made.')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person giving the testimonial.', max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating given by the student (1-5 stars).')),
                ('feedback_text', models.TextField(help_text='The actual feedback message.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the testimonial was submitted.')),
                ('email', models.EmailField(blank=True, help_text='Optional email of the author for contact.', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the yoga pose.', max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, help_text='The Sanskrit name of the pose.', max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='The difficulty level of the pose.', max_length=20)),
                ('description', models.TextField(help_text="A brief description of the pose's benefits and purpose.")),
                ('instructions', models.TextField(help_text='Step-by-step instructions for performing the pose.')),
                ('icon_class', models.CharField(help_text="Font Awesome icon class for the pose (e.g., 'fas fa-child').", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for the course.', max_digits=10)),
                ('reference', models.CharField(help_text='Unique transaction reference from payment gateway.', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment.', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment record was created.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was successfully verified.', null=True)),
                ('course', models.ForeignKey(blank=True, help_text='The course associated with this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='yoga_app.course')),
            ],
        ),
    ]
