# Generated by Django 5.2.3 on 2025-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathingtechnique',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='course',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='yogapose',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='breathingtechnique',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL for an image representing the technique (e.g., Unsplash link, placeholder).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL for an image representing the course (e.g., Unsplash link, placeholder).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL for an image representing the pose (e.g., Unsplash link, placeholder).', max_length=500, null=True),
        ),
    ]
