# Generated by Django 5.2.3 on 2025-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, help_text='Full course content visible only to enrolled users.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Reference generated by Paystack', max_length=100, null=True, unique=True),
        ),
    ]
