# Generated by Django 5.2.3 on 2025-06-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0005_course_content_payment_paystack_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_reference',
        ),
    ]
