# Generated by Django 5.2.3 on 2025-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0006_remove_course_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detailed_content',
            field=models.TextField(blank=True, help_text='Full, detailed content of the course (only visible to enrolled users).', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='A detailed description of the course content (visible to all).'),
        ),
    ]
