# Generated by Django 5.2.3 on 2025-06-30 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0007_course_detailed_content_alter_course_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when the course was marked as complete.')),
                ('course', models.ForeignKey(help_text='The course that was completed.', on_delete=django.db.models.deletion.CASCADE, to='yoga_app.course')),
                ('user', models.ForeignKey(help_text='The user who completed the course.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Course Completion',
                'verbose_name_plural': 'User Course Completions',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
