# Generated by Django 5.2.3 on 2025-07-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0008_usercoursecompletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='detailed_content',
            new_name='full_content',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='bio',
        ),
        migrations.AddField(
            model_name='breathingtechnique',
            name='video_url',
            field=models.URLField(blank=True, help_text='Embed URL for a video demonstration (e.g., YouTube embed link)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='video_url',
            field=models.URLField(blank=True, help_text='Embed URL for a video demonstration (e.g., YouTube embed link)', max_length=500, null=True),
        ),
    ]
