# Generated by Django 5.2.3 on 2025-07-02 17:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0009_rename_detailed_content_course_full_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='full_content',
            new_name='detailed_content',
        ),
        migrations.AddField(
            model_name='consultant',
            name='bio',
            field=models.TextField(default=django.utils.timezone.now, help_text='A short biography of the consultant.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='The associated Django User account.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating given by the user (1 to 5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional text comment for the review.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was submitted.')),
                ('course', models.ForeignKey(help_text='The course being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='yoga_app.course')),
                ('user', models.ForeignKey(help_text='The user who submitted the review.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-submitted_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
