# Generated by Django 5.2.3 on 2025-07-03 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0010_rename_full_content_course_detailed_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='detailed_content',
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, help_text='Any specific requests or questions for the session.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overview_content',
            field=models.TextField(blank=True, help_text='General overview content for the course, separate from structured lessons.', null=True),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the module (e.g., 'Module 1: Foundations of Yoga').", max_length=200)),
                ('description', models.TextField(blank=True, help_text="A brief description of the module's content.", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order of the module within the course.')),
                ('course', models.ForeignKey(help_text='The course this module belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='yoga_app.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the lesson (e.g., 'Lesson 1.1: Introduction to Asanas').", max_length=200)),
                ('content', models.TextField(help_text='The detailed content of the lesson (can include HTML/Markdown).')),
                ('video_url', models.URLField(blank=True, help_text='Embed URL for a video (e.g., YouTube embed link).', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order of the lesson within the module.')),
                ('module', models.ForeignKey(help_text='The module this lesson belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='yoga_app.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp when the lesson was marked as complete.')),
                ('lesson', models.ForeignKey(help_text='The lesson that was completed.', on_delete=django.db.models.deletion.CASCADE, to='yoga_app.lesson')),
                ('user', models.ForeignKey(help_text='The user who completed the lesson.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Lesson Completion',
                'verbose_name_plural': 'User Lesson Completions',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
