# Generated by Django 5.2.3 on 2025-07-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0011_remove_course_detailed_content_booking_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the discussion topic.', max_length=255)),
                ('content', models.TextField(help_text='The initial post content for the topic.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the topic was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the topic was last updated.')),
                ('course', models.ForeignKey(help_text='The course this topic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='yoga_app.course')),
                ('lesson', models.ForeignKey(blank=True, help_text='Optional: The specific lesson this topic relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_topics', to='yoga_app.lesson')),
                ('user', models.ForeignKey(help_text='The user who created this topic.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion Topic',
                'verbose_name_plural': 'Discussion Topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the discussion post.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last updated.')),
                ('parent_post', models.ForeignKey(blank=True, help_text='Optional: The parent post this is a reply to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='yoga_app.discussionpost')),
                ('user', models.ForeignKey(help_text='The user who created this post.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(help_text='The discussion topic this post belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='yoga_app.discussiontopic')),
            ],
            options={
                'verbose_name': 'Discussion Post',
                'verbose_name_plural': 'Discussion Posts',
                'ordering': ['created_at'],
            },
        ),
    ]
