# Generated by Django 5.2.3 on 2025-07-07 07:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathingtechnique',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="A brief description of the technique's benefits."),
        ),
        migrations.AlterField(
            model_name='breathingtechnique',
            name='instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Step-by-step instructions for performing the breathing technique.'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome icon class for the consultant (e.g., 'fas fa-user-md').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='A detailed description of the course content (visible to all).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='includes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="What the course includes (e.g., 'HD Videos', 'PDF Guides').", null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='General overview content for the course, separate from structured lessons.', null=True),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='The content of the discussion post.'),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='The initial post content for the topic.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='The detailed content of the lesson (can include HTML/Markdown).'),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="A brief description of the pose's benefits and purpose."),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Step-by-step instructions for performing the pose.'),
        ),
    ]
