# Generated by Django 5.2.3 on 2025-07-08 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0015_alter_breathingtechnique_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number for contact.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text="URL to the consultant's profile picture.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, help_text='Optional subject of the message.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the payment record was created in the system.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the payment record was last updated.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed_lesson',
            field=models.ForeignKey(blank=True, help_text='The last lesson this user viewed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_viewed_by', to='yoga_app.lesson'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the payment was successfully made.', null=True),
        ),
    ]
