# Generated by Django 5.2.3 on 2025-07-09 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0016_booking_phone_number_consultant_profile_picture_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursecompletion',
            name='course',
            field=models.ForeignKey(help_text='The course that was completed.', on_delete=django.db.models.deletion.CASCADE, related_name='user_completions', to='yoga_app.course'),
        ),
        migrations.AlterField(
            model_name='usercoursecompletion',
            name='user',
            field=models.ForeignKey(help_text='The user who completed the course.', on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the comment was last updated.')),
                ('lesson', models.ForeignKey(help_text='The lesson this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yoga_app.lesson')),
                ('user', models.ForeignKey(help_text='The user who posted the comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Comment',
                'verbose_name_plural': 'Lesson Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
