# Generated by Django 5.2.3 on 2025-07-09 12:27

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0017_alter_usercoursecompletion_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resources_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional resources for this lesson (e.g., PDF links, external articles).', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.CharField(choices=[('Morning (8am-12pm)', 'Morning (8pm-12pm)'), ('Afternoon (12pm-4pm)', 'Afternoon (12pm-4pm)'), ('Evening (4pm-8pm)', 'Evening (4pm-8pm)')], help_text='Preferred time slot for the session.', max_length=50),
        ),
    ]
