# Generated by Django 5.2.3 on 2025-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0018_lesson_resources_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="A short biography or 'about me' for the user.", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture.", null=True, upload_to='profile_pics/'),
        ),
    ]
