# Generated by Django 5.2.3 on 2025-07-12 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0019_userprofile_bio_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(db_index=True, help_text='Preferred date for the session.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.CharField(choices=[('Morning (8am-12pm)', 'Morning (8am-12pm)'), ('Afternoon (12pm-4pm)', 'Afternoon (12pm-4pm)'), ('Evening (4pm-8pm)', 'Evening (4pm-8pm)')], db_index=True, help_text='Preferred time slot for the session.', max_length=50),
        ),
        migrations.AlterField(
            model_name='breathingtechnique',
            name='name',
            field=models.CharField(db_index=True, help_text='The common name of the breathing technique.', max_length=100),
        ),
        migrations.AlterField(
            model_name='breathingtechnique',
            name='sanskrit_name',
            field=models.CharField(blank=True, db_index=True, help_text='The Sanskrit name of the technique.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the consultant.', max_length=100),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='specialty',
            field=models.CharField(db_index=True, help_text="Consultant's specialty (e.g., 'Yoga Therapist & Ayurveda Specialist').", max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email address of the sender.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the message was submitted.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as true to highlight this course as popular.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, help_text='Title of the yoga course.', max_length=200),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.IntegerField(db_index=True, help_text='Rating given by the user (1 to 5 stars).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the review was submitted.'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the post was created.'),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the topic was created.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='The display order of the lesson within the module.'),
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the comment was created.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='The display order of the module within the course.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the notification was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', 'New Reply'), ('like', 'New Like'), ('course_update', 'Course Update'), ('admin_message', 'Admin Message')], db_index=True, help_text='Type of notification.', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if the notification has been read.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the payment record was created in the system.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the payment was successfully made.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current status of the payment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True, help_text='Rating given by the student (1-5 stars).'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the testimonial was submitted.'),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='name',
            field=models.CharField(db_index=True, help_text='The common name of the yoga pose.', max_length=100),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='sanskrit_name',
            field=models.CharField(blank=True, db_index=True, help_text='The Sanskrit name of the pose.', max_length=100, null=True),
        ),
    ]
