# Generated by Django 5.2.3 on 2025-07-14 13:59

import django_ckeditor_5.fields
# import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0020_alter_booking_preferred_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the blog category.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the category name.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category.')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='Optional URL to link to the relevant content.', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('reply', 'Reply'), ('course_update', 'Course Update'), ('admin_message', 'Admin Message'), ('new_blog_post', 'New Blog Post'), ('blog_comment', 'Blog Comment')], help_text='Type of notification.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, help_text='Indicates if the notification has been read.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The user who triggered the notification (e.g., commenter, liker).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post.', max_length=200)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the post title.', max_length=200, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Full content of the blog post.')),
                ('excerpt', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='A short summary or excerpt of the blog post.')),
                ('featured_image', models.ImageField(blank=True, help_text='An optional featured image for the blog post.', null=True, upload_to='blog_images/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the post was published.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last updated.')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the blog post is publicly visible.')),
                ('author', models.ForeignKey(help_text='The user who authored this blog post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='The category this blog post belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='yoga_app.blogpostcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the comment.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the comment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the comment was last updated.')),
                ('user', models.ForeignKey(help_text='The user who posted the comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The blog post this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yoga_app.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
