# Generated by Django 5.2.3 on 2025-07-17 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0022_tag_alter_lessoncomment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='Users who liked this blog post.', related_name='liked_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', 'New Reply'), ('like', 'New Like'), ('course_update', 'Course Update'), ('admin_message', 'Admin Message'), ('new_blog_post', 'New Blog Post'), ('blog_comment', 'Blog Comment'), ('blog_post_like', 'Blog Post Like')], db_index=True, help_text='Type of notification.', max_length=50),
        ),
    ]
