# Generated by Django 5.2.3 on 2025-07-22 15:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0023_blogpost_likes_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="A brief description of the module's content.", null=True),
        ),
    ]
