# Generated by Django 5.2.3 on 2025-07-23 15:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0024_alter_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='A short biography of the consultant.'),
        ),
    ]
