# Generated by Django 5.2.3 on 2025-07-23 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0025_alter_consultant_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Indicates if the consultant is currently available for bookings.'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
