# Generated by Django 5.2.3 on 2025-07-24 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0026_consultant_created_at_consultant_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this testimonial has been approved for public display.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, help_text='Email of the person (optional, for internal contact).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='feedback_text',
            field=models.TextField(help_text='The actual testimonial or feedback message.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Optional rating from 1 to 5 stars.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the testimonial was submitted.'),
        ),
    ]
