# Generated by Django 5.2.3 on 2025-07-31 13:55

import datetime
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0027_alter_testimonial_options_testimonial_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breathingtechnique',
            options={'ordering': ['name'], 'verbose_name': 'Breathing Technique', 'verbose_name_plural': 'Breathing Techniques'},
        ),
        migrations.AlterModelOptions(
            name='consultant',
            options={'ordering': ['name'], 'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module__order', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='usercoursecompletion',
            options={'ordering': ['completed_at'], 'verbose_name': 'User Course Completion', 'verbose_name_plural': 'User Course Completions'},
        ),
        migrations.AlterModelOptions(
            name='userlessoncompletion',
            options={'ordering': ['completed_at'], 'verbose_name': 'User Lesson Completion', 'verbose_name_plural': 'User Lesson Completions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='yogapose',
            options={'ordering': ['name'], 'verbose_name': 'Yoga Pose', 'verbose_name_plural': 'Yoga Poses'},
        ),
        migrations.RemoveField(
            model_name='breathingtechnique',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='yogapose',
            name='instructions',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Consultant's contact email.", max_length=254),
        ),
        migrations.AddField(
            model_name='consultant',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Consultant's contact phone number.", max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Indicates if the message has been read by an admin.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Approximate duration of the lesson in minutes.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='If true, this lesson can be viewed as a preview without course enrollment.'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the subscription is active.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the notification was last updated (e.g., marked read).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text="User's physical address.", max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text="User's city.", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text="User's country.", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 31, 13, 55, 56, 548154, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth.", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, help_text="Link to user's Facebook profile."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_profile',
            field=models.URLField(blank=True, help_text="Link to user's Instagram profile."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text="Link to user's LinkedIn profile."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's contact phone number.", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_app_notifications',
            field=models.BooleanField(default=True, help_text='Whether to receive in-app notifications.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='receive_email_notifications',
            field=models.BooleanField(default=True, help_text='Whether to receive notifications via email.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.URLField(blank=True, help_text="Link to user's Twitter profile."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the post was published.', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='A URL-friendly version of the post title.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Title of the blog post.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='breathingtechnique',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed description of the technique, including benefits and instructions.'),
        ),
        migrations.AlterField(
            model_name='breathingtechnique',
            name='duration',
            field=models.CharField(blank=True, help_text="Recommended duration for practicing this technique (e.g., '5 minutes', '10 breaths').", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='breathingtechnique',
            name='name',
            field=models.CharField(db_index=True, help_text='The common name of the breathing technique.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Price of the course. Use 0.00 for free courses.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reply', 'New Reply'), ('like', 'New Like'), ('course_update', 'Course Update'), ('admin_message', 'Admin Message'), ('blog_comment', 'Blog Comment'), ('blog_post_like', 'Blog Post Like'), ('new_blog_post', 'New Blog Post')], db_index=True, help_text='Type of notification.', max_length=50),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed description of the pose, including benefits and instructions.'),
        ),
    ]
