# Generated by Django 5.2.3 on 2025-07-31 22:19

import datetime
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0028_alter_breathingtechnique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingtechnique',
            name='instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(default=datetime.datetime(2025, 7, 31, 22, 19, 38, 706038, tzinfo=datetime.timezone.utc), help_text='Step-by-step instructions for performing the technique.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yogapose',
            name='instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, help_text='Step-by-step instructions for performing the pose.'),
            preserve_default=False,
        ),
    ]
