# Generated by Django 5.2.3 on 2025-08-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0029_breathingtechnique_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_webp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_webp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
