# Generated by Django 5.2.3 on 2026-04-01 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0030_blogpost_featured_image_webp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image_webp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_webp',
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', '-published_date'], name='idx_blog_published'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='idx_blog_slug'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author'], name='idx_blog_author'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-is_popular', 'price'], name='idx_course_popular_price'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='idx_course_created'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_free'], name='idx_course_free'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['course', '-submitted_at'], name='idx_review_course'),
        ),
        migrations.AddIndex(
            model_name='coursereview',
            index=models.Index(fields=['rating'], name='idx_review_rating'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', '-created_at'], name='idx_notif_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='idx_notif_type'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status', '-created_at'], name='idx_payment_user_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='idx_payment_reference'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='idx_userprofile_user'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-created_at'], name='idx_userprofile_created'),
        ),
    ]
