# Generated by Django 5.2.3 on 2026-04-10 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0032_booking_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(choices=[('morning', 'Morning Awakening'), ('sleep', 'Sleep & Rest'), ('focus', 'Focus & Clarity'), ('healing', 'Healing & Recovery'), ('stress', 'Stress Relief'), ('gratitude', 'Gratitude & Joy'), ('chakra', 'Chakra Balancing'), ('breathwork', 'Breathwork')], db_index=True, default='morning', max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=20)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, help_text='Preparation and practice instructions.')),
                ('guided_by', models.CharField(blank=True, help_text='Name of the guide or teacher.', max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=10, help_text='Duration in minutes.')),
                ('audio_url', models.URLField(blank=True, help_text='Link to audio file or streaming URL.', max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('benefits', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meditation',
                'verbose_name_plural': 'Meditations',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['category', 'difficulty'], name='idx_meditation_cat_diff')],
            },
        ),
        migrations.CreateModel(
            name='Mudra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('sanskrit_name', models.CharField(blank=True, max_length=200)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=20)),
                ('associated_chakra', models.CharField(choices=[('root', 'Root (Muladhara)'), ('sacral', 'Sacral (Swadhisthana)'), ('solar_plexus', 'Solar Plexus (Manipura)'), ('heart', 'Heart (Anahata)'), ('throat', 'Throat (Vishuddha)'), ('third_eye', 'Third Eye (Ajna)'), ('crown', 'Crown (Sahasrara)'), ('all', 'All Chakras')], db_index=True, default='all', max_length=20)),
                ('description', models.TextField(help_text='Overview of the mudra and its significance.')),
                ('instructions', models.TextField(help_text='Step-by-step instructions for performing the mudra.')),
                ('benefits', models.TextField(blank=True, help_text='Physical, mental, and spiritual benefits.')),
                ('duration', models.CharField(blank=True, help_text="Recommended hold duration (e.g., '5–15 minutes').", max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mudra',
                'verbose_name_plural': 'Mudras',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['difficulty', 'associated_chakra'], name='idx_mudra_diff_chakra')],
            },
        ),
        migrations.CreateModel(
            name='Chakra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('root', 'Root'), ('sacral', 'Sacral'), ('solar_plexus', 'Solar Plexus'), ('heart', 'Heart'), ('throat', 'Throat'), ('third_eye', 'Third Eye'), ('crown', 'Crown')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveSmallIntegerField(help_text='Position 1 (root) to 7 (crown).', unique=True)),
                ('color', models.CharField(help_text="Associated colour name (e.g., 'Red', 'Indigo').", max_length=30)),
                ('color_hex', models.CharField(default='#855300', help_text='Hex colour code.', max_length=7)),
                ('element', models.CharField(blank=True, help_text='Associated element (Earth, Water, Fire, Air, Ether, Light, Thought).', max_length=50)),
                ('location', models.CharField(blank=True, help_text="Body location (e.g., 'Base of spine').", max_length=100)),
                ('seed_mantra', models.CharField(blank=True, help_text='Bija mantra (e.g., LAM, VAM, RAM).', max_length=20)),
                ('description', models.TextField()),
                ('signs_of_balance', models.TextField(blank=True)),
                ('signs_of_imbalance', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('associated_breathing', models.ManyToManyField(blank=True, related_name='chakras', to='yoga_app.breathingtechnique')),
                ('associated_poses', models.ManyToManyField(blank=True, related_name='chakras', to='yoga_app.yogapose')),
                ('associated_mudras', models.ManyToManyField(blank=True, related_name='chakras', to='yoga_app.mudra')),
            ],
            options={
                'verbose_name': 'Chakra',
                'verbose_name_plural': 'Chakras',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DailyPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('mood_before', models.CharField(blank=True, choices=[('1', 'Struggling'), ('2', 'Low'), ('3', 'Neutral'), ('4', 'Good'), ('5', 'Radiant')], max_length=1)),
                ('mood_after', models.CharField(blank=True, choices=[('1', 'Struggling'), ('2', 'Low'), ('3', 'Neutral'), ('4', 'Good'), ('5', 'Radiant')], max_length=1)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Total session duration in minutes.')),
                ('notes', models.TextField(blank=True, help_text='Personal reflections or notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breathing_techniques', models.ManyToManyField(blank=True, related_name='daily_practices', to='yoga_app.breathingtechnique')),
                ('poses', models.ManyToManyField(blank=True, related_name='daily_practices', to='yoga_app.yogapose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_practices', to=settings.AUTH_USER_MODEL)),
                ('meditations', models.ManyToManyField(blank=True, related_name='daily_practices', to='yoga_app.meditation')),
                ('mudras', models.ManyToManyField(blank=True, related_name='daily_practices', to='yoga_app.mudra')),
            ],
            options={
                'verbose_name': 'Daily Practice',
                'verbose_name_plural': 'Daily Practices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='idx_dailypractice_user_date')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
