# Generated by Django 5.2.3 on 2026-04-12 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0033_add_mudra_meditation_chakra_dailypractice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current status of the booking.', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Internal notes from the teacher (not visible to the student).'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'preferred_date'], name='idx_booking_status_date'),
        ),
    ]
