# Generated by Django 5.2.3 on 2026-04-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0034_booking_status_teacher_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingtechnique',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image for the technique (takes priority over image_url when set).', null=True, upload_to='breathing/'),
        ),
        migrations.AddField(
            model_name='chakra',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image (takes priority over image_url).', null=True, upload_to='chakras/'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Uploaded profile picture (takes priority over profile_picture_url when set).', null=True, upload_to='consultants/'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image for the course (takes priority over image_url when set).', null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='meditation',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image (takes priority over image_url).', null=True, upload_to='meditations/'),
        ),
        migrations.AddField(
            model_name='mudra',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image (takes priority over image_url).', null=True, upload_to='mudras/'),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image for the pose (takes priority over image_url when set).', null=True, upload_to='poses/'),
        ),
    ]
