# Generated by Django 5.2.3 on 2026-04-12 21:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

# ── PostgreSQL trigger functions ──────────────────────────────────────────────
# Each trigger keeps search_vector in sync automatically on INSERT/UPDATE.
# Weights: A = name/title (highest), B = sanskrit_name/instructor, C = description

_YOGAPOSE_TRIGGER_FUNC = """
CREATE OR REPLACE FUNCTION yoga_app_yogapose_search_vector_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.sanskrit_name, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C');
    RETURN NEW;
END;
$$;
"""

_YOGAPOSE_TRIGGER = """
DROP TRIGGER IF EXISTS yoga_app_yogapose_search_vector_trigger ON yoga_app_yogapose;
CREATE TRIGGER yoga_app_yogapose_search_vector_trigger
BEFORE INSERT OR UPDATE ON yoga_app_yogapose
FOR EACH ROW EXECUTE FUNCTION yoga_app_yogapose_search_vector_update();
"""

_BREATHING_TRIGGER_FUNC = """
CREATE OR REPLACE FUNCTION yoga_app_breathingtechnique_search_vector_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.sanskrit_name, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C');
    RETURN NEW;
END;
$$;
"""

_BREATHING_TRIGGER = """
DROP TRIGGER IF EXISTS yoga_app_breathing_search_vector_trigger ON yoga_app_breathingtechnique;
CREATE TRIGGER yoga_app_breathing_search_vector_trigger
BEFORE INSERT OR UPDATE ON yoga_app_breathingtechnique
FOR EACH ROW EXECUTE FUNCTION yoga_app_breathingtechnique_search_vector_update();
"""

_COURSE_TRIGGER_FUNC = """
CREATE OR REPLACE FUNCTION yoga_app_course_search_vector_update()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.instructor_name, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C');
    RETURN NEW;
END;
$$;
"""

_COURSE_TRIGGER = """
DROP TRIGGER IF EXISTS yoga_app_course_search_vector_trigger ON yoga_app_course;
CREATE TRIGGER yoga_app_course_search_vector_trigger
BEFORE INSERT OR UPDATE ON yoga_app_course
FOR EACH ROW EXECUTE FUNCTION yoga_app_course_search_vector_update();
"""

# Backfill existing rows after adding the column
_YOGAPOSE_BACKFILL = """
UPDATE yoga_app_yogapose SET search_vector =
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(sanskrit_name, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C');
"""

_BREATHING_BACKFILL = """
UPDATE yoga_app_breathingtechnique SET search_vector =
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(sanskrit_name, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C');
"""

_COURSE_BACKFILL = """
UPDATE yoga_app_course SET search_vector =
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(instructor_name, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C');
"""


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0035_add_imagefields_to_content_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingtechnique',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='breathingtechnique',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_breathing_search_vector'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_course_search_vector'),
        ),
        migrations.AddIndex(
            model_name='yogapose',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_yogapose_search_vector'),
        ),
        # Create trigger functions and triggers
        migrations.RunSQL(_YOGAPOSE_TRIGGER_FUNC + _YOGAPOSE_TRIGGER),
        migrations.RunSQL(_BREATHING_TRIGGER_FUNC + _BREATHING_TRIGGER),
        migrations.RunSQL(_COURSE_TRIGGER_FUNC + _COURSE_TRIGGER),
        # Backfill existing rows
        migrations.RunSQL(_YOGAPOSE_BACKFILL),
        migrations.RunSQL(_BREATHING_BACKFILL),
        migrations.RunSQL(_COURSE_BACKFILL),
    ]
