# Generated by Django 5.2.3 on 2026-04-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0036_add_search_vector_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KriyaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('sanskrit_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('energising', 'Energising'), ('cleansing', 'Cleansing & Detox'), ('grounding', 'Grounding'), ('heart_opening', 'Heart Opening'), ('kundalini', 'Kundalini Awakening'), ('morning', 'Morning Practice'), ('evening', 'Evening Wind-Down'), ('healing', 'Healing & Recovery'), ('chakra', 'Chakra Activation')], db_index=True, default='energising', max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], db_index=True, default='Beginner', max_length=20)),
                ('description', models.TextField(help_text='Overview of the kriya, its purpose and effects.')),
                ('benefits', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Total estimated duration in minutes.')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kriyas/')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kriya Session',
                'verbose_name_plural': 'Kriya Sessions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'difficulty'], name='idx_kriya_cat_diff')],
            },
        ),
        migrations.CreateModel(
            name='KriyaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Position in the sequence (1 = first).')),
                ('step_type', models.CharField(choices=[('pose', 'Yoga Pose'), ('breathing', 'Breathing Technique'), ('mudra', 'Mudra'), ('meditation', 'Meditation')], db_index=True, max_length=15)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text="Duration for this step in seconds (0 = use the element's default).")),
                ('repetitions', models.PositiveSmallIntegerField(default=1, help_text='Number of repetitions for this step.')),
                ('instruction_note', models.TextField(blank=True, help_text='Optional specific instruction for this step within the kriya context.')),
                ('breathing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kriya_steps', to='yoga_app.breathingtechnique')),
                ('kriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='yoga_app.kriyasession')),
                ('meditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kriya_steps', to='yoga_app.meditation')),
                ('mudra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kriya_steps', to='yoga_app.mudra')),
                ('pose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kriya_steps', to='yoga_app.yogapose')),
            ],
            options={
                'verbose_name': 'Kriya Step',
                'verbose_name_plural': 'Kriya Steps',
                'ordering': ['kriya', 'order'],
                'unique_together': {('kriya', 'order')},
            },
        ),
    ]
