# Generated by Django 5.2.3 on 2026-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0037_add_kriya_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypractice',
            name='kriyas',
            field=models.ManyToManyField(blank=True, related_name='daily_practices', to='yoga_app.kriyasession'),
        ),
    ]
