# Generated by Django 5.2.3 on 2026-04-13 20:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0038_dailypractice_add_kriyas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriyasession',
            name='benefits',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='kriyasession',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Overview of the kriya, its purpose and effects.'),
        ),
        migrations.AlterField(
            model_name='kriyastep',
            name='instruction_note',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional specific instruction for this step within the kriya context.'),
        ),
    ]
