# Generated by Django 5.2.3 on 2026-07-09 13:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_app', '0040_remove_search_vector_from_sqlite_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='breathingtechnique',
            name='idx_breathing_search_vector',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='idx_course_search_vector',
        ),
        migrations.RemoveIndex(
            model_name='yogapose',
            name='idx_yogapose_search_vector',
        ),
        migrations.RemoveField(
            model_name='breathingtechnique',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='course',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='yogapose',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='yogapose',
            name='benefits',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Key benefits of this pose.', null=True),
        ),
        migrations.AddField(
            model_name='yogapose',
            name='contraindications',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Contraindications and precautions for this pose.', null=True),
        ),
    ]
